package com.example.demo

import com.example.demo.data.ApiClient
import com.example.demo.BuildConfig

class MainActivity

// Regression guard for a false positive this check once produced.
//
// BuildConfig is GENERATED by AGP and has no source declaration anywhere, so a
// source-only scan cannot find it. Before the generated-symbol allowlist existed,
// this import made the check fail on a file that compiles perfectly.
//
// It lives in fixed/ deliberately: if the allowlist is ever removed, this fixture
// stops exiting 0 and selftest says so.
